// <copyright file="UrlPathEncodingTests.cs" company="GSD Logic">
// Copyright © 2024 GSD Logic. All rights reserved.
// </copyright>

namespace GSD.Extensions.Http.UnitTests;

using Xunit;

/// <summary>
/// Provides unit tests for the <see cref="UrlPathEncoding" /> class.
/// </summary>
public class UrlPathEncodingTests
{
    /// <summary>
    /// Tests the <see cref="UrlPathEncoding" /> class for encoding and decoding URL path segments.
    /// </summary>
    /// <param name="input">The original input string containing slashes or tildes.</param>
    /// <param name="expected">The expected encoded string after escaping the input.</param>
    [Theory]
    [InlineData("", "")]
    [InlineData("/", "~1")]
    [InlineData("//", "~2")]
    [InlineData("///", "~3")]
    [InlineData("////", "~3~1")]
    [InlineData("/0/1/2/", "~10~11~12~1")]
    [InlineData("/a/b/c/", "~1a~1b~1c~1")]
    [InlineData("/~", "~1~0")]
    [InlineData("/~/~", "~1~0~1~0")]
    [InlineData("/~~", "~1~0~0")]
    [InlineData("/~~~", "~1~0~0~0")]
    [InlineData("0/1/2", "0~11~12")]
    [InlineData("0/1~2", "0~11~02")]
    [InlineData("0//1//2", "0~21~22")]
    [InlineData("0//~//1//~//2", "0~2~0~21~2~0~22")]
    [InlineData("a/b/c", "a~1b~1c")]
    [InlineData("a/b~c", "a~1b~0c")]
    [InlineData("a//b//c", "a~2b~2c")]
    [InlineData("a//~//b//~//c", "a~2~0~2b~2~0~2c")]
    [InlineData("a~b~c", "a~0b~0c")]
    [InlineData("~", "~0")]
    [InlineData("~/", "~0~1")]
    [InlineData("~//", "~0~2")]
    [InlineData("~///", "~0~3")]
    [InlineData("~0", "~00")]
    [InlineData("~1", "~01")]
    [InlineData("~2", "~02")]
    [InlineData("~3", "~03")]
    [InlineData("~0~1~2~", "~00~01~02~0")]
    [InlineData("~a~b~c~", "~0a~0b~0c~0")]
    [InlineData("~~", "~0~0")]
    [InlineData("~~0", "~0~00")]
    [InlineData("~~//", "~0~0~2")]
    [InlineData("~~///", "~0~0~3")]
    [InlineData("~~~/", "~0~0~0~1")]
    [InlineData("~~~", "~0~0~0")]
    [InlineData("~~~///", "~0~0~0~3")]
    [InlineData("~~~//~/~", "~0~0~0~2~0~1~0")]
    [InlineData("~~~~", "~0~0~0~0")]
    [InlineData("///~~~", "~3~0~0~0")]
    [InlineData("//~~", "~2~0~0")]
    [InlineData("~/~/", "~0~1~0~1")]
    [InlineData("escaped~1string", "escaped~01string")]
    [InlineData("some/really/long/path/with/many/segments", "some~1really~1long~1path~1with~1many~1segments")]
    [InlineData("http://www.example.com/~", "http:~2www.example.com~1~0")]
    [InlineData("http://www.example.com/some/path/", "http:~2www.example.com~1some~1path~1")]
    [InlineData("http://www.example.com/some~path", "http:~2www.example.com~1some~0path")]
    public void ConvertPreservesOriginalString(string input, string expected)
    {
        var intermediate = UrlPathEncoding.Escape(input);
        Assert.DoesNotContain('/', intermediate);
        Assert.DoesNotContain("%2F", intermediate, StringComparison.Ordinal);
        Assert.Equal(expected, intermediate);

        var result = UrlPathEncoding.Unescape(intermediate);
        Assert.Equal(input, result);
    }

    /// <summary>
    /// Tests the <see cref="UrlPathEncoding" /> class for decoding special use cases.
    /// </summary>
    /// <param name="input">The input string that cannot be generated by encoding.</param>
    /// <param name="expected">The expected decoded string.</param>
    [Theory]
    [InlineData("some~really~long~path~with~many~segments", "some/really/long/path/with/many/segments")]
    public void UnescapeConvertsSpecialCases(string input, string expected)
    {
        var result = UrlPathEncoding.Unescape(input);
        Assert.Equal(expected, result);
    }
}