//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSD.Extensions.DataFormats.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSD.Extensions.DataFormats.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array must have a length of 16..
        /// </summary>
        internal static string ArgumentException_ArrayMustHaveLengthOf16 {
            get {
                return ResourceManager.GetString("ArgumentException_ArrayMustHaveLengthOf16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is out of bounds for the array or {1} is greater than the number of elements from {0} to the end of the array..
        /// </summary>
        internal static string ArgumentException_Invalid_Offset_Length {
            get {
                return ResourceManager.GetString("ArgumentException_Invalid_Offset_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count is too big..
        /// </summary>
        internal static string ArgumentOutOfRangeException_CountIsTooBig {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_CountIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be non-negative..
        /// </summary>
        internal static string ArgumentOutOfRangeException_NonNegativeRequired_Parameter {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_NonNegativeRequired_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step must be greater than zero..
        /// </summary>
        internal static string ArgumentOutOfRangeException_StepMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_StepMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version must be either 3 or 5..
        /// </summary>
        internal static string ArgumentOutOfRangeException_VersionMustBe3Or5 {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_VersionMustBe3Or5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many bytes in what should have been a 7 bit encoded Int32..
        /// </summary>
        internal static string FormatException_Invalid7BitEncodedInt32 {
            get {
                return ResourceManager.GetString("FormatException_Invalid7BitEncodedInt32", resourceCulture);
            }
        }
    }
}
