//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSD.Extensions.Http.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSD.Extensions.Http.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpClient.Timeout must be Timeout.InfiniteTimeSpan..
        /// </summary>
        internal static string ArgumentException_HttpClient_Timeout_Must_Be_Timeout_InfiniteTimeSpan {
            get {
                return ResourceManager.GetString("ArgumentException_HttpClient_Timeout_Must_Be_Timeout_InfiniteTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal base64url string..
        /// </summary>
        internal static string ArgumentException_Illegal_Base64Url_String {
            get {
                return ResourceManager.GetString("ArgumentException_Illegal_Base64Url_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during an HTTP client request..
        /// </summary>
        internal static string HttpClientException_DefaultMessage {
            get {
                return ResourceManager.GetString("HttpClientException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout property can only be modified before sending the first request..
        /// </summary>
        internal static string HttpClientException_NotFirstRequest {
            get {
                return ResourceManager.GetString("HttpClientException_NotFirstRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request timed out..
        /// </summary>
        internal static string TimeoutException_TheRequestTimedOut {
            get {
                return ResourceManager.GetString("TimeoutException_TheRequestTimedOut", resourceCulture);
            }
        }
    }
}
